from tkinter import *
import smtplib
import time

screen = Tk()
screen.geometry('600x600')
screen.title('E-mail sender')

# Functions
# Clock function
def clock():
    global clock
    # Setting up clock
    hour=time.strftime("%H")
    minute=time.strftime("%M")
    second=time.strftime("%S")
    day = time.strftime("%A")
    Clock.config(text=hour + ":" + minute + ":" + second)
    Clock.after(1000, clock)
    day_label.config(text=day)
# Quit function
def Quit_button_function():
    # Destroys the screen
    screen.destroy()
def Failed_quit_button_function():
    screen.destroy()
def Send_email_button_function():
    def Next_button_first_function():
        def Next_button_second_function():
            def Next_button_third_function():
                Message_email = Your_message_input.get()
                def Quit_button_success_function():
                    screen.destroy()
                def Again_button_function():
                    Email_confirmation_message.pack_forget()
                    blank8.pack_forget()
                    blank9.pack_forget()
                    blank10.pack_forget()
                    blank11.pack_forget()
                    blank12.pack_forget()
                    blank13.pack_forget()
                    blank14.pack_forget()
                    blank15.pack_forget()
                    blank16.pack_forget()
                    blank17.pack_forget()
                    blank18.pack_forget()
                    blank19.pack_forget()
                    Quit_button_success.pack_forget()
                    Again_button.pack_forget()
                    blank1.pack()
                    welcome_message.pack()
                    blank2.pack()
                    Send_email_button.pack()
                    blank3.pack()
                    Quit_button.pack()
                    blank4.pack()
                    blank5.pack(side=RIGHT)
                    blank6.pack(side=LEFT)
                    day_label.pack(side=LEFT)
                    Clock.pack(side=RIGHT)
                    clock()
                while True:
                    try:
                       server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
                       server.login(Users_email, Users_password)
                       server.sendmail(Users_email, Receivers_email, Message_email)
                       server.quit()
                       Your_message_input.pack_forget()
                       Your_message_label.pack_forget()
                       blank16.pack_forget()
                       blank17.pack_forget()
                       Next_button_third.pack_forget()
                       Welcome_message_2_second.pack_forget()
                       Welcome_message_2.pack_forget()
                       Email_confirmation_message = Label(screen, text="E-mail has been send")
                       Email_confirmation_message.config(font=('Aerial', 35))
                       Email_confirmation_message.pack()
                       blank18 = Label(screen, text=" ")
                       blank18.config(font=('Aerial', 80))
                       blank18.pack()
                       Again_button = Button(screen, text="Again", command=lambda: Again_button_function())
                       Again_button.config(font=('Aerial', 30))
                       Again_button.pack()
                       blank19 = Label(screen, text=" ")
                       blank19.config(font=('Aerial', 33))
                       blank19.pack()
                       Quit_button_success = Button(screen, text="Quit", command=lambda: Quit_button_success_function())
                       Quit_button_success.config(font=('Aerial', 30))
                       Quit_button_success.pack()
                       break
                    except:
                       def Failed_again_button_function():
                           global Failed_again_button_function
                           blank20.pack_forget()
                           blank21.pack_forget()
                           blank22.pack_forget()
                           blank23.pack_forget()
                           Failed_again_button.pack_forget()
                           Failed_quit_button.pack_forget()
                           Failed_email_message_second.pack_forget()
                           Failed_email_message.pack_forget()
                           Send_email_button_function()
                       blank13.pack_forget()
                       blank16.pack_forget()
                       blank17.pack_forget()
                       Your_message_input.pack_forget()
                       Your_message_label.pack_forget()
                       Next_button_third.pack_forget()
                       Welcome_message_2.pack_forget()
                       Welcome_message_2_second.pack_forget()
                       blank20 = Label(screen, text=" ")
                       blank20.config(font=('Aerial', 10))
                       blank20.pack()
                       Failed_email_message = Label(screen, text="Your e-mail has not been send")
                       Failed_email_message.config(font=('Aerial', 30))
                       Failed_email_message.pack()
                       blank21 = Label(screen, text=" ")
                       blank21.config(font=('Aerial', 5))
                       blank21.pack()
                       Failed_email_message_second = Label(screen, text="You typed something wrong")
                       Failed_email_message_second.config(font=('Aerial', 30))
                       Failed_email_message_second.pack()
                       blank22 = Label(screen, text=" ")
                       blank22.config(font=('Aerial', 100))
                       blank22.pack()
                       Failed_again_button = Button(screen, text="Again", command=lambda: Failed_again_button_function())
                       Failed_again_button.config(font=('Aerial', 30))
                       Failed_again_button.pack()
                       blank23 = Label(screen, text=" ")
                       blank23.config(font=('Aerial', 20))
                       blank23.pack()
                       Failed_quit_button = Button(screen, text="Quit", command=lambda: Failed_quit_button_function())
                       Failed_quit_button.config(font=('Aerial', 30))
                       Failed_quit_button.pack()
                       break
            Receivers_email = Your_receiver_input.get()
            blank14.pack_forget()
            blank15.pack_forget()
            Next_button_second.pack_forget()
            Your_receiver_label.pack_forget()
            Your_receiver_input.pack_forget()
            Your_message_label = Label(screen, text="Message")
            Your_message_label.config(font=('Aerial', 25))
            Your_message_label.pack()
            blank16 = Label(screen, text=" ")
            blank16.config(font=('Aerial', 10))
            blank16.pack()
            Your_message_input = Entry(screen, width=24)
            Your_message_input.config(font=('Aerial', 28))
            Your_message_input.pack()
            blank17 = Label(screen, text=" ")
            blank17.config(font=('Aerial', 50))
            blank17.pack()
            Next_button_third = Button(screen, text="Send e-mail", command=lambda: Next_button_third_function())
            Next_button_third.config(font=('Aerial', 30))
            Next_button_third.pack()

        # Getting input of entry widgets
        Users_email = Your_email_input.get()
        Users_password = Your_password_input.get()
        # Deleting all the stuff
        blank8.pack_forget()
        blank9.pack_forget()
        blank10.pack_forget()
        blank11.pack_forget()
        blank12.pack_forget()
        Your_password_input.pack_forget()
        Your_email_label.pack_forget()
        Your_email_input.pack_forget()
        Your_password_label.pack_forget()
        Next_button_first.pack_forget()
        # Interface
        blank13 = Label(screen, text=" ")
        blank13.config(font=('Aerial', 30))
        blank13.pack()
        Your_receiver_label = Label(screen, text="Receiver's e-mail")
        Your_receiver_label.config(font=('Aerial', 25))
        Your_receiver_label.pack()
        blank14 = Label(screen, text=" ")
        blank14.config(font=('Aerial', 10))
        blank14.pack()
        Your_receiver_input = Entry(screen, width=24)
        Your_receiver_input.config(font=('Aerial', 28))
        Your_receiver_input.pack()
        blank15 = Label(screen, text=" ")
        blank15.config(font=('Aerial', 50))
        blank15.pack()
        Next_button_second = Button(screen, text="Next", command=lambda: Next_button_second_function())
        Next_button_second.config(font=('Aerial', 30))
        Next_button_second.pack()
    # Deleting all the stuff(almost)
    blank1.pack_forget()
    blank2.pack_forget()
    blank3.pack_forget()
    blank4.pack_forget()
    blank5.pack_forget()
    blank6.pack_forget()
    welcome_message.pack_forget()
    Quit_button.pack_forget()
    Send_email_button.pack_forget()
    day_label.pack_forget()
    Clock.pack_forget()
    # New interface
    Welcome_message_2 = Label(screen, text="Enter data for sending")
    Welcome_message_2.config(font=('Aerial', 35))
    Welcome_message_2.pack()
    Welcome_message_2_second = Label(screen, text="e-mail")
    Welcome_message_2_second.config(font=('Aerial', 35))
    Welcome_message_2_second.pack()
    blank8 = Label(screen, text=" ")
    blank8.config(font=('Aerial', 30))
    blank8.pack()
    Your_email_label = Label(screen, text="Your e-mail")
    Your_email_label.config(font=('Aerial', 25))
    Your_email_label.pack()
    blank9 = Label(screen, text=" ")
    blank9.config(font=('Aerial', 2))
    blank9.pack()
    Your_email_input = Entry(screen, width=24)
    Your_email_input.config(font=('Aerial', 28))
    Your_email_input.pack()
    blank10 = Label(screen, text=" ")
    blank10.config(font=('Aerial', 5))
    blank10.pack()
    Your_password_label = Label(screen, text="Your password")
    Your_password_label.config(font=('Aerial', 25))
    Your_password_label.pack()
    blank11 = Label(screen, text=" ")
    blank11.config(font=('Aerial', 2))
    blank11.pack()
    Your_password_input = Entry(screen, width=24)
    Your_password_input.config(font=('Aerial', 28))
    Your_password_input.pack()
    blank12 = Label(screen, text=" ")
    blank12.config(font=('Aerial', 15))
    blank12.pack()
    Next_button_first = Button(screen, text="Next", command=lambda: Next_button_first_function())
    Next_button_first.config(font=('Aerial', 30))
    Next_button_first.pack()

# interface
blank1 = Label(screen, text=" ")
blank1.config(font=('Aerial', 20))
blank1.pack()
welcome_message = Label(screen, text="E-mail sender")
welcome_message.config(font=('Aerial', 50))
welcome_message.pack()
blank2 = Label(screen, text=" ")
blank2.config(font=('Aerial', 100))
blank2.pack()
Send_email_button = Button(screen, text="Send email", command=lambda: Send_email_button_function())
Send_email_button.config(font=('Aerial', 30))
Send_email_button.pack()
blank3 = Label(screen, text=" ")
blank3.config(font=('Aerial', 20))
blank3.pack()
Quit_button = Button(screen, text="Quit", command=lambda: Quit_button_function())
Quit_button.config(font=('Aerial', 30))
Quit_button.pack()
blank4 = Label(screen, text=" ")
blank4.config(font=('Aerial', 20))
blank4.pack()
blank5 = Label(screen, text=" ")
blank5.config(font=('Aerial', 40))
blank5.pack(side=RIGHT)
blank6 = Label(screen, text=" ")
blank6.config(font=('Aerial', 30))
blank6.pack(side=LEFT)
day_label = Label(screen, text="")
day_label.config(font=('Aerial', 30))
day_label.pack(side=LEFT)
Clock = Label(screen, text="", fg="white", bg="black")
Clock.config(font=('Aerial', 25))
Clock.pack(side=RIGHT)
clock()

screen.mainloop()